apiVersion: v1
kind: DeploymentConfig
metadata:
  name: clamav
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: clamav
    spec:
      containers:
      - image: clamav
        name: clamav
        ports:
        - containerPort: 3310
          protocol: TCP
      restartPolicy: Always
  selector:
    name: clamav
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - clamav
      from:
        kind: ImageStreamTag
        name: clamav:latest
    type: ImageChange
  strategy:
    type: Rolling
